name: Trigger auto deployment for mayorcontainerapp

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  # push:
  #   branches: 
  #     [ main ]
  #   paths:
  #   - '**'
  #   - '.github/workflows/mayorcontainerapp-AutoDeployTrigger-2f9a9702-dfe5-44f9-a714-2bbe11ef9f5d.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.MAYORCONTAINERAPP_AZURE_CREDENTIALS }}

      - name: Log in to Azure Container Registry
        run: |
          echo ${{ secrets.MAYORCONTAINERAPP_REGISTRY_PASSWORD  }} | docker login --username ${{ secrets.MAYORCONTAINERAPP_REGISTRY_USERNAME }} --password-stdin rgbicepregistry.azurecr.io

        # Update Azure Container App using Azure CLI
      - name: Update Container App
        run: |
          az containerapp update \
            -n scanning-service \
            -g RG-Bicep \
            --image rgbicepregistry.azurecr.io/rgbicepregistry.azurecr.io/mayorapptest:3 \
            --container-name mayorcontainerapp \
            --replace-env-vars SPRING_PROFILES_ACTIVE=cloud APPLICATIONINSIGHTS_ROLE_NAME=scanning-service  SERVER_PORT=8080  

    
        #  # Step 6: Split traffic for blue-green deployment
      # - name: Configure traffic splitting
      #   run: |
      #     # Get the latest revision (green)
      #     GREEN_REVISION=$(az containerapp revision list \
      #       -n malwarescanning-service \
      #       -g rg-x4-malwarescanning \
      #       --query "[?active==null].{name:name}" -o tsv | head -n 1)
          
      #     # Get the current active revision (blue)
      #     BLUE_REVISION=$(az containerapp revision list \
      #       -n malwarescanning-service \
      #       -g rg-x4-malwarescanning \
      #       --query "[?active==true].{name:name}" -o tsv | head -n 1)

      #     echo "Blue revision: $BLUE_REVISION"
      #     echo "Green revision: $GREEN_REVISION"

      #     # Split traffic: 50% to blue, 50% to green
      #     az containerapp ingress traffic set \
      #       -n malwarescanning-service \
      #       -g rg-x4-malwarescanning \
      #       --traffic-weight $BLUE_REVISION=50 $GREEN_REVISION=50
          

      # - name: Build and push container image to registry
      #   uses: azure/container-apps-deploy-action@v2
      #   with:
      #     # appSourcePath: ${{ github.workspace }}
      #     # _dockerfilePathKey_: _dockerfilePath_
      #     registryUrl: rgbicepregistry.azurecr.io
      #     registryUsername: ${{ secrets.MAYORCONTAINERAPP_REGISTRY_USERNAME }}
      #     registryPassword: ${{ secrets.MAYORCONTAINERAPP_REGISTRY_PASSWORD }}
      #     containerAppName: mayorcontainerapp
      #     resourceGroup: RG-Bicep
      #     # imageToDeploy: rgbicepregistry.azurecr.io/rgbicepregistry.azurecr.io/mayorapptest:${{ github.sha }}
      #     imageToDeploy: rgbicepregistry.azurecr.io/mayorapptest:4
      #     #imageToDeploy: rgbicepregistry.azurecr.io/rgbicepregistry.azurecr.io/mayorapptest:7db4cc36536a55edf78c25595162bfeb679989dc
          
            

     

